### ISSUE TITLE
大佬，编译不过啊

### ISSUE THREAD

**Issue by wangdemon** [xia-chu/TcpProxy#2]
报错如下图所示

![2023-02-17 18-19-21 的屏幕截图](https://user-images.githubusercontent.com/20681339/219617631-10ce0d25-b498-49ab-a779-faaec66c0216.png)

**Comment by xia-chu** [comment]
加下头文件:
#include<sys/types.h>
#include<sys/wait.h>

**Comment by wangdemon** [comment]
客户端一直连接不上服务器。

客户端运行
![1](https://user-images.githubusercontent.com/20681339/220258919-0cdaaef2-538b-4164-a5a3-9010ee241712.png)

服务端运行
![2](https://user-images.githubusercontent.com/20681339/220258956-3647904d-39d7-4855-9222-74b0e8ba9bb6.png)


客户端配置文件
![3](https://user-images.githubusercontent.com/20681339/220258987-757637d0-6267-484e-bdba-bdbbe5e0c048.png)


服务器配置文件
![4](https://user-images.githubusercontent.com/20681339/220259015-c571f2fa-9678-467a-98cf-09e42fcc2af9.png)

**Comment by xia-chu** [comment]
请查看帮助：
TcpProxyClient -h

**Comment by wangdemon** [comment]
感谢大佬的无私奉献。现在客户端可以连接服务器了。

我把服务器部署在腾讯云主机上

客户端部署在自己的乌班图主机上

客户端可以连接服务器，但是通过浏览器，还是无法访问google

**Comment by xia-chu** [comment]
这个不是vpn软件啊 TcpProxyClient -a google.com:443 -l 127.0.0.1:443
然后设置host文件 google.com指向127.0.0.1，然后访问google.com试试

**Comment by xia-chu** [comment]
不过你这种用法 原理上基本可行 但是我重来没这样试过

**Comment by xia-chu** [comment]
这个工具本来是方便让你访问nat内主机的 跟frp功能类似

**Comment by wangdemon** [comment]
感谢大佬
